groups:
  - name: elb-http
    rules:
    - alert: ELBHighHTTPResponseTime
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} HTTP response time > 500 ms'
        description: 'Average Layer 7 response time (m14_l7_rt) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 500 ms. Current: {{ "{{ $value }}" }} ms'
      expr: |
        elb_m14_l7_rt > 500
      labels:
        severity: warning
    - alert: ELBVeryHighHTTPResponseTime
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} HTTP response time > 1000 ms'
        description: 'Average Layer 7 response time (m14_l7_rt) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 1000 ms. Current: {{ "{{ $value }}" }} ms'
      expr: |
        elb_m14_l7_rt > 1000
      labels:
        severity: critical

  - name: elb-usage
    rules:
    - alert: ELBHighLayer4ConnectionUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 4 connection usage > 80%'
        description: 'Layer 4 concurrent connections (l4_con_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l4_con_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer4InboundBandwidthUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 4 inbound bandwidth usage > 80%'
        description: 'Layer 4 inbound bandwidth (l4_in_bps_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l4_in_bps_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer4OutboundBandwidthUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 4 outbound bandwidth usage > 80%'
        description: 'Layer 4 outbound bandwidth (l4_out_bps_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l4_out_bps_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer7ConnectionUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 7 connection usage > 80%'
        description: 'Layer 7 concurrent connections (l7_con_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l7_con_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer7InboundBandwidthUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 7 inbound bandwidth usage > 80%'
        description: 'Layer 7 inbound bandwidth (l7_in_bps_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l7_in_bps_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer7OutboundBandwidthUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 7 outbound bandwidth usage > 80%'
        description: 'Layer 7 outbound bandwidth (l7_out_bps_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l7_out_bps_usage > 0.8
      labels:
        severity: warning
    - alert: ELBHighLayer7NewConnectionUsage
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} layer 7 new connection usage > 80%'
        description: 'Layer 7 new connection usage (l7_ncps_usage) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 80%. Current: {{ "{{ $value }}" }}%'
      expr: |
        elb_l7_ncps_usage > 0.8
      labels:
        severity: warning

  - name: elb-backend-server-health
    rules:
    - alert: ELBUnhealthyBackendServers
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} unhealthy backend servers > 0'
        description: 'Number of unhealthy backend servers (m9_abnormal_servers) for ELB {{ "{{ $labels.loadbalancer }}" }} is > 0. Current: {{ "{{ $value }}" }}'
      expr: |
        elb_m9_abnormal_servers > 0
      labels:
        severity: warning
    - alert: ELBAllBackendServersUnhealthy
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} all backend servers unhealthy'
        description: 'All backend servers for ELB {{ "{{ $labels.loadbalancer }}" }} are unhealthy if m9_abnormal_servers == (m9_abnormal_servers + ma_normal_servers).'
      expr: |
        elb_m9_abnormal_servers == (elb_m9_abnormal_servers + elb_ma_normal_servers)
      labels:
        severity: critical

  - name: elb-server-latency
    rules:
    - alert: ELBHighBackendResponseTime
      annotations:
        summary: '{{ "{{ $labels.loadbalancer }}" }} backend response time > 1000 ms'
        description: 'Average backend response time (m17_l7_upstream_rt) for ELB {{ "{{ $labels.loadbalancer }}" }} has exceeded 1000 ms. Current: {{ "{{ $value }}" }} ms'
      expr: |
        elb_m17_l7_upstream_rt > 1000
      labels:
        severity: warning