{
 "title": "BMS - Bare Metal Server",
 "tags": [ "OTC" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "label_values({__name__=~\"bms_.*\"}, resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(Agent) Idle CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_idle{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Other Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_other{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Kernel Space CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_system{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) User Space CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_user{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Nice Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_nice{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) iowait Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_iowait{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) CPU Interrupt Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_irq{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) CPU Software Interrupt Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_cpu_usage_softirq{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) 1-Minute Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_load_average1{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) 5-Minute Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_load_average5{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) 15-Minute Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_load_average15{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mem_available{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_mem_usedpercent{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Idle Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mem_free{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mem_buffers{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mem_cached{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_free{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk Storage Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_total{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_used{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_usedpercent{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disks Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_agt_read_bytes_rate{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disks Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_agt_read_requests_rate{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disks Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_agt_write_bytes_rate{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disks Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_mountpointprefix_disk_agt_write_requests_rate{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Average Read Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_readtime{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Average Write Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_writetime{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_disk_ioutils{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_queue_length{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Average Disk Write Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_write_bytes_per_operation{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Average Disk Read Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_read_bytes_per_operation{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk I/O Service Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_io_svctm{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) File System Read/Write Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_fs_rwstate{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Disk inode Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_inodestotal{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Total inode Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bms_disk_inodesused{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Percentage of Total inode Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_disk_inodesusedpercent{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "bms_net_bitrecv{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "bms_net_bitsent{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) NIC Packet Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "bms_net_packetrecv{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) NIC Packet Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "bms_net_packetsent{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Receive Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_net_errin{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Transmit Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_net_errout{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Received Packet Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_net_dropin{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "(Agent) Transmitted Packet Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bms_net_dropout{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}