{
 "title": "DCS - Distributed Cache Service",
 "tags": [ "OTC" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "label_values({__name__=~\"dcs_.*\"}, resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The monitored object's maximum CPU usage among multiple sampling values in a monitoring period\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_cpu_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Maximum Command Latency",
   "type": "timeseries",
   "description": "Maximum latency of commands\n\nUnit: ms",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dcs_command_max_delay{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "timeseries",
   "description": "Number of connections received during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_total_connections_received{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Slow Query Logs",
   "type": "timeseries",
   "description": "Existence of slow query logs in the instance\n\n\n\n**Note:**\n\nSlow queries caused by the **MIGRATE**, **SLAVEOF**, **CONFIG**, **BGSAVE**, and **BGREWRITEAOF** commands are not counted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_is_slow_log_exist{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory consumed by the monitored object\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_memory_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Keys With an Expiration",
   "type": "timeseries",
   "description": "Number of keys with an expiration in Redis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_expires{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "description": "Ratio of the number of Redis cache hits to the number of lookups. Calculation: keyspace_hits/(keyspace_hits + keyspace_misses)\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_keyspace_hits_perc{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "description": "Number of bytes used by the Redis server\n\nUnit: KB, MB, or byte (configurable on the console)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_used_memory{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory Dataset",
   "type": "timeseries",
   "description": "Dataset memory that the Redis server has used\n\nUnit: KB, MB, or byte (configurable on the console)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_used_memory_dataset{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory Dataset Ratio",
   "type": "timeseries",
   "description": "Percentage of dataset memory that server has used\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_used_memory_dataset_perc{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory RSS",
   "type": "timeseries",
   "description": "Resident set size (RSS) memory that the Redis server has used, which is the memory that actually resides in the memory, including all stack and heap memory but not swapped-out memory\n\nUnit: KB, MB, or byte (configurable on the console)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_used_memory_rss{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Ops per Second",
   "type": "timeseries",
   "description": "Number of commands processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_instantaneous_ops{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Keyspace Misses",
   "type": "timeseries",
   "description": "Number of failed lookups of keys in the main dictionary during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_keyspace_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "description": "Number of keys in Redis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_keys{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Flow Control Times",
   "type": "timeseries",
   "description": "Number of flow control times during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_rx_controlled{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "description": "Percentage of the maximum bandwidth limit used (the average value of the sum of input and output flows)\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_bandwidth_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "description": "Percentage of the current number of connections to the maximum allowed number of connections\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_connections_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Instance Node Status",
   "type": "timeseries",
   "description": "Status of instance nodes. If the status is normal, the value is **0**. If the status is abnormal, the value is **1**.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_instance node status{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Maximum Latency",
   "type": "timeseries",
   "description": "Maximum delay from when the node receives commands to when it responds\n\nUnit: μs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_command_max_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Average delay from when the node receives commands to when it responds\n\nUnit: μs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_command_avg_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Current average usage of CPU resources\n\nUnit: %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_cpu_avg_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "timeseries",
   "description": "Number of clients suspended by block operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_blocked_clients{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "description": "Number of connected clients (excluding those from slave nodes)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_connected_clients{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "DEL",
   "type": "timeseries",
   "description": "Number of **DEL** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_del{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "timeseries",
   "description": "Number of keys that have been evicted and deleted during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_evicted_keys{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "EXPIRE",
   "type": "timeseries",
   "description": "Number of **EXPIRE** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_expire{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "timeseries",
   "description": "Number of keys that have expired and been deleted during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_expired_keys{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "GET",
   "type": "timeseries",
   "description": "Number of **GET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_get{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "HDEL",
   "type": "timeseries",
   "description": "Number of **HDEL** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_hdel{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "HGET",
   "type": "timeseries",
   "description": "Number of **HGET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_hget{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "HMGET",
   "type": "timeseries",
   "description": "Number of **HMGET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_hmget{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "HMSET",
   "type": "timeseries",
   "description": "Number of **HMSET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_hmset{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "HSET",
   "type": "timeseries",
   "description": "Number of **HSET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_hset{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Input Flow",
   "type": "timeseries",
   "description": "Instantaneous input traffic\n\nUnit: KB/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "dcs_instantaneous_input_kbps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Output Flow",
   "type": "timeseries",
   "description": "Instantaneous output traffic\n\nUnit: KB/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "dcs_instantaneous_output_kbps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Memory Fragmentation Ratio",
   "type": "timeseries",
   "description": "Ratio between Used Memory RSS and Used Memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_memory_frag_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "MGET",
   "type": "timeseries",
   "description": "Number of **MGET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_mget{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "MSET",
   "type": "timeseries",
   "description": "Number of **MSET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_mset{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "PubSub Channels",
   "type": "timeseries",
   "description": "Number of Pub/Sub channels",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_pubsub_channels{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "PubSub Patterns",
   "type": "timeseries",
   "description": "Number of Pub/Sub patterns",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_pubsub_patterns{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "SET",
   "type": "timeseries",
   "description": "Number of **SET** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_set{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory Lua",
   "type": "timeseries",
   "description": "Number of bytes used by the Lua engine\n\nUnit: KB, MB, or byte (configurable on the console)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_used_memory_lua{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Memory Peak",
   "type": "timeseries",
   "description": "Peak memory consumed by Redis since the Redis server last started\n\nUnit: KB, MB, or byte (configurable on the console)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_used_memory_peak{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "SADD",
   "type": "timeseries",
   "description": "Number of **SADD** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_sadd{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "SMEMBERS",
   "type": "timeseries",
   "description": "Number of **SMEMBERS** commands processed per second\n\nUnit: count/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_smembers{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Client Longest Output List",
   "type": "timeseries",
   "description": "Longest output list among current client connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_client_longest_out_list{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Client Biggest Input Buf",
   "type": "timeseries",
   "description": "Maximum input data length among current client connections\n\nUnit: byte",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_client_biggest_in_buf{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Commands Processed",
   "type": "timeseries",
   "description": "Number of commands processed during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_total_commands_processed{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Input Bytes",
   "type": "timeseries",
   "description": "Number of bytes received during the monitoring period\n\nUnit: byte",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_total_net_input_bytes{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Output Bytes",
   "type": "timeseries",
   "description": "Number of bytes sent during the monitoring period\n\nUnit: byte",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_total_net_output_bytes{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Rejected Connections",
   "type": "timeseries",
   "description": "Number of connections that have exceeded maxclients and been rejected during the monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_rejected_connections{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Replication Gap",
   "type": "timeseries",
   "description": "Data synchronization gap between the master and the replica",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_ms_repl_offset{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Instance Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_node_status{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "aof_current_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_aof_current_size{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "auth_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_auth_errors{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_io_util_avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_disk_device_io_util_avg{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_io_util_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_disk_device_io_util_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_read_requests_rate_avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_disk_device_read_requests_rate_avg{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_read_requests_rate_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_disk_device_read_requests_rate_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_write_requests_rate_avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_disk_device_write_requests_rate_avg{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_device_write_requests_rate_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_disk_device_write_requests_rate_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_io_rt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dcs_disk_io_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_io_timeout_cnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_disk_io_timeout_cnt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "disk_util_inband",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_disk_util_inband{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "keyspace_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_keyspace_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "latest_fork_usec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dcs_latest_fork_usec{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_aof_current_size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_aof_current_size{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_auth_cmds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_auth_cmds{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_auth_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_auth_errors{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cas_badval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cas_badval{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cas_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cas_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cas_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cas_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cmd_flush",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cmd_flush{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cmd_get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cmd_get{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cmd_set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cmd_set{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_cmd_touch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_cmd_touch{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_command_max_delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dcs_mc_command_max_delay{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_commands_processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_commands_processed{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_connected_clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_connected_clients{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_connections_received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_connections_received{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_curr_items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_curr_items{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_decr_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_decr_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_decr_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_decr_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_delete_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_delete_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_delete_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_delete_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_evicted_keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 337 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_evicted_keys{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_expired_keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 345 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_expired_keys{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_get_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 345 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_get_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_get_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 353 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_get_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_incr_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 353 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_incr_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_incr_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 361 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_incr_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_instantaneous_input_kbps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 361 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "dcs_mc_instantaneous_input_kbps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_instantaneous_ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 369 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_mc_instantaneous_ops{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_instantaneous_output_kbps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 369 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "dcs_mc_instantaneous_output_kbps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_is_slow_log_exist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 377 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_is_slow_log_exist{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_keyspace_hits_perc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 377 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_mc_keyspace_hits_perc{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_memory_frag_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 385 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_mc_memory_frag_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_net_input_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 385 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_net_input_bytes{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_net_output_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 393 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_net_output_bytes{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_rejected_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 393 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_rejected_connections{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_sync_full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_sync_full{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_sync_partial_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_sync_partial_err{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_sync_partial_ok",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 409 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_sync_partial_ok{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_touch_hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 409 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_touch_hits{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_touch_misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 417 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_mc_touch_misses{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_used_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 417 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_used_memory{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_used_memory_peak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 425 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_used_memory_peak{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mc_used_memory_rss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 425 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_mc_used_memory_rss{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "net_in_throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 433 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcs_net_in_throughput{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "net_out_throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 433 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcs_net_out_throughput{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "network_rt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 441 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dcs_network_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "network_timeout_cnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 441 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_network_timeout_cnt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "node_reboot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 449 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_node_reboot{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 449 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_scan{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "setex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 457 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dcs_setex{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "slave_psyncing_opid_gap_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 457 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_slave_psyncing_opid_gap_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "slave_state_abnormal_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 465 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_slave_state_abnormal_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "slow_log_counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 465 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_slow_log_counts{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "storage_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 473 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcs_storage_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "sync_full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 473 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_sync_full{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "sync_partial_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 481 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_sync_partial_err{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "sync_partial_ok",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 481 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dcs_sync_partial_ok{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "sys_available_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 489 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_sys_available_memory{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "used_storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 489 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dcs_used_storage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}