{
 "title": "DDM - Distributed Database Middleware",
 "tags": [ "OTC" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "label_values({__name__=~\"ddms_.*\"}, resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_cpu_util{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_mem_util{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Input Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_bytes_in{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Output Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_bytes_out{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_qps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_read_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_write_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Slow SQL Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_slow_log{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_rt_avg{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_connections{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_backend_connection_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_active_connections{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_connection_util{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Kernel Full GC Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_kernel_fgc_cnt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "DDM Node Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_node_status_alarm_code{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Global Secondary Sequences Beyond Threshold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ddms_ddm_global_sequence_threshold_exceeded_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "ddm_rw_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ddms_ddm_rw_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}