{
 "title": "DWS - Data Warehouse Service",
 "tags": [ "OTC" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "label_values({__name__=~\"dws_.*\"}, resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Ratio of requested data that already exists in the cache. It is the ratio of the amount of data that already exists in the cache to the total amount of requested data. A higher cache hit ratio means higher cache usage of the system, fewer times that data needs to be read from the disk or network, and faster system response speed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws001_shared_buffer_hit_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "In-memory Sort Ratio",
   "type": "timeseries",
   "description": "Ratio of the extra memory space used by the sorting algorithm to the memory space occupied by the sorted data. In a merge sort, for example, the size of the merge buffer is often proportional to the size of the sorted data, so the in-memory ratio is usually between 10% and 50%.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws002_in_memory_sort_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "File Reads",
   "type": "timeseries",
   "description": "Total number of database file reads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dws_dws003_physical_reads{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "File Writes",
   "type": "timeseries",
   "description": "Total number of database file writes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dws_dws004_physical_writes{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "File Reads per Second",
   "type": "timeseries",
   "description": "Number of database file reads per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dws_dws005_physical_reads_per_second{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "File Writes per Second",
   "type": "timeseries",
   "description": "Number of database file writes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dws_dws006_physical_writes_per_second{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Data Volume",
   "type": "timeseries",
   "description": "Total data volume of the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "dws_dws007_db_size{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Active SQL Count",
   "type": "timeseries",
   "description": "Number of active SQLs in the database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dws_dws008_active_sql_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Session Count",
   "type": "timeseries",
   "description": "Number of sessions that access the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dws_dws009_session_count{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws010_cpu_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each node in a cluster, in percentage\n\n\n\n**Note:**\n\nAfter the console is upgraded to 8.3.0.202, the memory usage includes the memory occupied by the cache. Therefore, the value of this metric increases compared with that before the upgrade.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws011_mem_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Number of I/O requests processed by each node in the cluster per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "dws_dws012_iops{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Input Throughput",
   "type": "timeseries",
   "description": "Data input to each node in the cluster per second over the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dws_dws013_bytes_in{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Network Output Throughput",
   "type": "timeseries",
   "description": "Data sent to the network per second from each node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dws_dws014_bytes_out{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Disk usage of each node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws015_disk_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Total Disk Size",
   "type": "timeseries",
   "description": "Total disk space of each node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "dws_dws016_disk_total_size{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "description": "Used disk space of each node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "dws_dws017_disk_used_size{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "timeseries",
   "description": "Data volume read from each disk in the cluster per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dws_dws018_disk_read_throughput{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "timeseries",
   "description": "Data volume written to each disk in the cluster per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dws_dws019_disk_write_throughput{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Time per Disk Read",
   "type": "timeseries",
   "description": "Average time used each time when a disk reads data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dws_dws020_avg_disk_sec_per_read{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Time per Disk Write",
   "type": "timeseries",
   "description": "Average time used each time when data is written to a disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dws_dws021_avg_disk_sec_per_write{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Disk Queue Length",
   "type": "timeseries",
   "description": "Average I/O queue length of a disk",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dws_dws022_avg_disk_queue_length{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "DN I/O usage",
   "type": "timeseries",
   "description": "Average disk I/O usage of DNs in a cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws_024_dn_diskio_util{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "dws_023_avg_diskio_util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dws_dws_023_avg_diskio_util{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}