{
 "title": "ELB - Elastic Load Balancing",
 "tags": [ "OTC" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "resource_name",
    "label": "Resource",
    "query": "label_values({__name__=~\"elb_.*\"}, resource_name)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m1_cps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m2_act_conn{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Inactive Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m3_inact_conn{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m4_ncps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Incoming Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m5_in_pps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m6_out_pps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Inbound Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "elb_m7_in_bps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Outbound Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "elb_m8_out_bps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Unhealthy Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m9_abnormal_servers{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Healthy Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_ma_normal_servers{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Reset Packets from Backend Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m1e_server_rps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Reset Packets from Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m21_client_rps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Reset Packets from Load Balancers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_m1f_lvs_rps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m22_in_bandwidth{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m23_out_bandwidth{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_mb_l7_qps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 3xx Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_md_l7_http_3xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "2xx Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_mc_l7_http_2xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 4xx Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_me_l7_http_4xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 5xx Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_mf_l7_http_5xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 Other Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m10_l7_http_other_status{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 404 Not Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m11_l7_http_404{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 499 Client Closed Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m12_l7_http_499{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 502 Bad Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m13_l7_http_502{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Layer-7 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m14_l7_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "4xx Status Codes Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m15_l7_upstream_4xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "5xx Status Codes Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m16_l7_upstream_5xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Average Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m17_l7_upstream_rt{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Maximum Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m1a_l7_upstream_rt_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Minimum Server Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m1b_l7_upstream_rt_min{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Maximum Layer-7 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m1c_l7_rt_max{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Minimum Layer-7 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m1d_l7_rt_min{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 Concurrent Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_con_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 Inbound Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_in_bps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 Outbound Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_out_bps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-7 New Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_ncps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer 7 QPS Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_qps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-4 Concurrent Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l4_con_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-4 Inbound Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l4_in_bps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-4 Outbound Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l4_out_bps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Layer-4 New Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l4_ncps_usage{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "client_tls_negotiation_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_client_tls_negotiation_error{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "dropped_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_dropped_connections{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "dropped_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_dropped_packets{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "dropped_traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_dropped_traffic{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_2xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_3xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_400",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_400{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_404",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_404{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_408",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_408{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_499",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_499{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_4xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_502",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_502{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_503",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_503{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_504",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_504{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "elb_http_5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_elb_http_5xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "ipgroup_blocked_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_ipgroup_blocked_packets{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "ipgroup_blocked_traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_ipgroup_blocked_traffic{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_2xx_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_2xx_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_4xx_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_4xx_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_5xx_ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "elb_l7_5xx_ratio{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_101",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_101{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_400",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_400{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_403",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_403{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_404",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_404{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_500{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_501",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_501{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_502",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_502{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_503",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_503{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_504",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_504{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "l7_upstream_other_status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_l7_upstream_other_status{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m17_l7_upstream_rt_p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m17_l7_upstream_rt_p90{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m17_l7_upstream_rt_p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m17_l7_upstream_rt_p95{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m17_l7_upstream_rt_p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "elb_m17_l7_upstream_rt_p99{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m18_l7_upstream_2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m18_l7_upstream_2xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m19_l7_upstream_3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_m19_l7_upstream_3xx{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m24_l7_req_Bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m24_l7_req_bps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m25_l7_resp_Bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 305 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m25_l7_resp_bps{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m26_in_bandwidth_ipv6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m26_in_bandwidth_ipv6{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "m27_out_bandwidth_ipv6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 313 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "elb_m27_out_bandwidth_ipv6{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mirror_in_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_mirror_in_packets{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mirror_in_traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_mirror_in_traffic{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mirror_out_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_mirror_out_packets{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "mirror_out_traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "elb_mirror_out_traffic{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "upstream_tls_negotiation_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "elb_upstream_tls_negotiation_error{resource_name=~\"$resource_name\"}",
     "legendFormat": "{{resource_name}}"
    }
   ]
  }
 ]
}