// gen-metrics fetches all OTC Cloud Eye documentation RST files and generates
// provider/metric_help_gen.go with MetricHelpStrings.
//
// Usage: go run ./cmd/gen-metrics --output provider/metric_help_gen.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/iits-consulting/otc-prometheus-exporter/otcdoc"
)

// otcNamespace resolves the OTC namespace string (e.g. "SYS.ECS") for a source.
// It prefers the namespace parsed directly from the RST file. When the RST has no
// "Namespace" section, it falls back to a known-exceptions map, then to "SYS.<UPPER>".
func otcNamespace(ds otcdoc.DocumentationSource, parsedNs string) string {
	if parsedNs != "" {
		return parsedNs
	}
	// RST files that don't declare a namespace section, or where the OTC namespace
	// differs from the simple "SYS.<upper(namespace)>" pattern.
	exceptions := map[string]string{
		"css": "SYS.ES",   // OTC publishes CSS metrics under SYS.ES
		"ddm": "SYS.DDMS", // RST and Huawei catalog both use SYS.DDMS
	}
	if ns, ok := exceptions[ds.Namespace]; ok {
		return ns
	}
	return "SYS." + strings.ToUpper(ds.Namespace)
}

// prometheusPrefix converts an OTC namespace (e.g. "SYS.NAT", "SERVICE.BMS") to the
// Prometheus metric name prefix used by PrometheusMetricName (e.g. "nat", "bms").
func prometheusPrefix(otcNs string) string {
	ns := strings.TrimPrefix(otcNs, "SYS.")
	ns = strings.TrimPrefix(ns, "SERVICE.")
	return strings.ToLower(ns)
}

func main() {
	output := flag.String("output", "provider/metric_help_gen.go", "path to write the generated file")
	flag.Parse()

	// helpStrings maps prometheus metric name → description string.
	helpStrings := map[string]string{}

	for _, ds := range otcdoc.DocumentationSources {
		fmt.Printf("fetching %s ...\n", ds.GithubRawUrl)
		page, err := otcdoc.FetchDocumentationSource(ds)
		if err != nil {
			log.Printf("WARN: %v — skipping\n", err)
			continue
		}

		ns := otcNamespace(ds, page.Namespace)
		prefix := prometheusPrefix(ns)

		added := 0
		for _, m := range page.Metrics {
			if m.Description == "" {
				continue
			}
			pname := prefix + "_" + strings.ToLower(m.MetricId)
			if _, exists := helpStrings[pname]; !exists {
				helpStrings[pname] = m.Description
				added++
			}
		}
		fmt.Printf("  → namespace=%s prefix=%s metrics=%d help_strings=%d\n", ns, prefix, len(page.Metrics), added)

		if ds.HuaweiFallbackUrl == "" {
			continue
		}

		// Huawei catalog: add help strings for metrics absent from the OTC RST.
		fmt.Printf("fetching huawei catalog %s ...\n", ds.HuaweiFallbackUrl)
		huaweiMetrics, err := otcdoc.FetchMarkdownMetrics(ds.HuaweiFallbackUrl)
		if err != nil {
			log.Printf("WARN: %v — skipping huawei fallback\n", err)
			continue
		}
		huaweiAdded := 0
		for _, m := range huaweiMetrics {
			pname := prefix + "_" + strings.ToLower(m.MetricId)
			// Only add if not already covered by the RST pass (RST descriptions take precedence).
			if _, exists := helpStrings[pname]; !exists && m.MetricId != "" {
				// Huawei catalog has no descriptions; set an empty string as a placeholder
				// so the metric is at least known. Descriptions come from the RST pass only.
				helpStrings[pname] = ""
				huaweiAdded++
			}
		}
		fmt.Printf("  → huawei fallback: +%d new metric names\n", huaweiAdded)
	}

	// Drop entries with empty descriptions — they add no value to the Help field.
	for k, v := range helpStrings {
		if v == "" {
			delete(helpStrings, k)
		}
	}

	src, err := buildSource(helpStrings, *output)
	if err != nil {
		log.Fatalf("build source: %v", err)
	}
	if err := os.WriteFile(*output, src, 0644); err != nil {
		log.Fatalf("write %s: %v", *output, err)
	}
	fmt.Printf("wrote %s (%d help strings)\n", *output, len(helpStrings))
}

func buildSource(helpStrings map[string]string, outputPath string) ([]byte, error) {
	// Sort keys for a stable, diff-friendly output.
	keys := make([]string, 0, len(helpStrings))
	for k := range helpStrings {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/gen-metrics — DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Sources: https://github.com/opentelekomcloud-docs (fetched %s)\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&buf, "// Regenerate with: make generate\n\n")
	fmt.Fprintf(&buf, "package provider\n\n")
	fmt.Fprintf(&buf, "// MetricHelpStrings maps a Prometheus metric name to its OTC documentation description.\n")
	fmt.Fprintf(&buf, "// Used by EnrichWithHelp to populate the Help field on scraped MetricFamily objects.\n")
	fmt.Fprintf(&buf, "var MetricHelpStrings = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", k, helpStrings[k])
	}
	fmt.Fprintf(&buf, "}\n")

	return format.Source(buf.Bytes())
}
