// gen-metrics fetches all OTC Cloud Eye documentation RST files and generates
// provider/metric_help_gen.go with MetricHelpStrings.
//
// Usage: go run ./cmd/gen-metrics --output provider/metric_help_gen.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/iits-consulting/otc-prometheus-exporter/otcdoc"
)

func main() {
	output := flag.String("output", "provider/metric_help_gen.go", "path to write the generated file")
	flag.Parse()

	// helpStrings maps prometheus metric name → description string.
	helpStrings := map[string]string{}

	for _, ds := range otcdoc.DocumentationSources {
		fmt.Printf("fetching %s ...\n", ds.GithubRawUrl)
		page, err := otcdoc.FetchDocumentationSource(ds)
		if err != nil {
			log.Printf("WARN: %v — skipping\n", err)
			continue
		}

		ns := otcdoc.OTCNamespace(ds, page.Namespace)
		prefix := otcdoc.PrometheusPrefix(ns)

		added := 0
		for _, m := range page.Metrics {
			if m.Description == "" {
				continue
			}
			pname := prefix + "_" + strings.ToLower(m.MetricId)
			if _, exists := helpStrings[pname]; !exists {
				helpStrings[pname] = m.Description
				added++
			}
		}
		fmt.Printf("  → namespace=%s prefix=%s metrics=%d help_strings=%d\n", ns, prefix, len(page.Metrics), added)

		if ds.HuaweiFallbackUrl == "" {
			continue
		}

		// Huawei catalog: add help strings for metrics absent from the OTC RST.
		fmt.Printf("fetching huawei catalog %s ...\n", ds.HuaweiFallbackUrl)
		huaweiMetrics, err := otcdoc.FetchMarkdownMetrics(ds.HuaweiFallbackUrl)
		if err != nil {
			log.Printf("WARN: %v — skipping huawei fallback\n", err)
			continue
		}
		huaweiAdded := 0
		for _, m := range huaweiMetrics {
			if m.MetricId == "" {
				continue
			}
			pname := prefix + "_" + strings.ToLower(m.MetricId)
			// Only add if not already covered by the RST pass (RST descriptions take precedence).
			if _, exists := helpStrings[pname]; !exists {
				helpStrings[pname] = m.Description
				huaweiAdded++
			}
		}
		fmt.Printf("  → huawei fallback: +%d new metric names\n", huaweiAdded)
	}

	src, err := buildSource(helpStrings, *output)
	if err != nil {
		log.Fatalf("build source: %v", err)
	}
	if err := os.WriteFile(*output, src, 0644); err != nil {
		log.Fatalf("write %s: %v", *output, err)
	}
	fmt.Printf("wrote %s (%d help strings)\n", *output, len(helpStrings))
}

func buildSource(helpStrings map[string]string, outputPath string) ([]byte, error) {
	// Sort keys for a stable, diff-friendly output.
	keys := make([]string, 0, len(helpStrings))
	for k := range helpStrings {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/gen-metrics — DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Sources: https://github.com/opentelekomcloud-docs (fetched %s)\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&buf, "// Regenerate with: go run ./cmd/gen-metrics --output provider/metric_help_gen.go\n\n")
	fmt.Fprintf(&buf, "package provider\n\n")
	fmt.Fprintf(&buf, "// MetricHelpStrings maps a Prometheus metric name to its OTC documentation description.\n")
	fmt.Fprintf(&buf, "// Used by EnrichWithHelp to populate the Help field on scraped MetricFamily objects.\n")
	fmt.Fprintf(&buf, "var MetricHelpStrings = map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", k, helpStrings[k])
	}
	fmt.Fprintf(&buf, "}\n")

	return format.Source(buf.Bytes())
}
